- .changeset/grumpy-emus-joke.md
- packages/analytics/README.md
- packages/analytics/index.tsx
---
Support passing options to `usePageviewAnalytics` so that we can support multiple "sites" served from a single app.
```ts
import usePageviewAnalytics from '@hashicorp/platform-analytics'
usePageviewAnalytics({
siteId: process.env.NEXT_PUBLIC_FATHOM_SITE_ID_WAYPOINT,
includedDomains: productData.analyticsConfig.includedDomains
})
```
> feat(analytics): support passing options to usePageviewAnalytics

- .changeset/slimy-months-obey.md
- packages/next-optimized-images/lib/index.js
---
This PR updates our patched version of `next-optimized-images` to support Next.js v12, which slightly tweaked the Webpack loader config used to load images. You can see the [v11 version here](https://github.com/vercel/next.js/blob/v11.1.4/packages/next/build/webpack/config/blocks/css/index.ts#L288-L313), and compare against the [v12 version here](https://github.com/vercel/next.js/blob/v12.0.9/packages/next/build/webpack/config/blocks/css/index.ts#L393-L412).
> feat: update Webpack rule removal logic to support Next.js v12

- .changeset/wet-parents-guess.md
- packages/analytics/index.tsx
This PR introduces a check for `navigator.sendBeacon` before the Fathom server-side script loads. If `navigator.sendBeacon` exists, the script continues as normal. If not, the script short-circuits.
This check ensures that `navigator.sendBeacon`, a method used by the server-side Fathom script, is present before the script attempts to execute it.  If the script attempts execution and fails, the page the user is visiting will 404.
> enhance(analytics): sendBeacon check before script load

- .changeset/new-comics-fly.md
- package-lock.json
- packages/cli/config/.eslintrc.js
- packages/cli/next-hashicorp
- packages/cli/package.json
---
- `babel-eslint` is deprecated, and `eslint-config-next`, which we are extending, provides a parser for us.
- Ensure fixes made by ESLint are output to their respective files
> feat: rely on eslint-config-next's parser

- .changeset/khaki-pans-repair.md
- packages/tools/README.md
- packages/tools/src/__tests__/index.test.ts
- packages/tools/src/index.ts
---
Adds `--resolve-paths` option, defaulting to true, which allows us to opt out of leveraging `tsconfig-paths/register` to resolve based on `baseUrl` and `paths` from `tsconfig.json`.
> feat(tools): adds --resolve-paths option, defaults to true

- .changeset/seven-shoes-boil.md
- package-lock.json
- packages/packer-plugins/README.md
- packages/packer-plugins/__tests__/index.test.ts
- packages/packer-plugins/constants.ts
- packages/packer-plugins/fetch-dev-plugin-docs.ts
- packages/packer-plugins/fetch-plugin-docs.ts
- packages/packer-plugins/index.ts
- packages/packer-plugins/package.json
- packages/packer-plugins/parse-docs-zip.ts
- packages/packer-plugins/parse-source-zip.ts
- packages/packer-plugins/types.ts
- packages/packer-plugins/validate-plugin-docs-files.ts
- readme.md
---
Abstracting out the utilities related to fetching content for packer plugins defined in a manifest file. I need access to these so that I can properly execute search indexing for packer in our shared workflows.
This was almost entirely lifted from https://github.com/hashicorp/dev-portal/tree/477e007fa880922170643001b1811aa49577fa83/src/components/_proxied-dot-io/packer/remote-plugin-docs, with a conversion to TS along the way.
> feat(platform-packer-plugins): abstract our packer plugins util

- .changeset/ninety-cobras-speak.md
- package-lock.json
- packages/types/README.md
- packages/types/package.json
- packages/types/utilities.d.ts
---
Adds utility types to `platform-types`. Since `index.d.ts` is added to the global scope of all projects, I decided instead to add the utility types to `/utilities`, in the hope that would prevent unnecessary build-time increases.
---
- https://app.asana.com/0/0/1202143884614326
> feat: add utility types

- packages/cli/config/.eslintrc.js
- Adds the [`no-nested-ternary`](https://eslint.org/docs/rules/no-nested-ternary) and [`no-unneeded-ternary`](https://eslint.org/docs/rules/no-unneeded-ternary) rules to our widely shared ESLint config. Also adds comments above them explaining why.
- Both rules are set to "warn" so they don't break other projects. The long term goal would be to set these to "error".
**Problems these rules solve:**
- `no-nested-ternary` is used for prohibiting nested ternaries, which I have a very difficult time reading and understanding, even after reading the same one multiple times.
- `no-unneeded-ternary` encourages simpler operations when a ternary has two boolean values in it or when something like `x ? x : 1` is written instead of `x || 1`. Saw it I was reading the docs for `no-nested-ternary` and …
> Add no-nested-ternary and no-unneeded-ternary to ESLint rules

- .changeset/cool-boats-taste.md
- packages/types/index.d.ts
---
Adds the module declarations to our platform types package that allow for the importing of modules that aren't exported by `framer-motion`'s `exports` configuration.
> feat: allow imports from framer-motion across exports boundary

- .changeset/clever-snakes-yawn.md
- packages/nextjs-plugin/src/plugins/with-framer-motion-esmodules-disabled.js
---
This PR updates the test for framer-motion and react-motion-config to account for the fact that motion-config paths in `react-components` doesn't use the `react-` prefix.
> fix: add support for motion-config paths from react-components

- .changeset/nasty-schools-peel.md
- packages/analytics/index.tsx
- packages/analytics/use-error-page-analytics/index.tsx
🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1202865459293217/f)
---
It was recently discovered that, across our various web properties, we make the following call:
`window.analytics.track(window.location.href, { ... } )`
The first parameter of the `track` method is used downstream in our various data warehouses to create a new table. Since we're using `window.location.href`, we're creating a table for _every_ URL that 404s. This is not ideal for analytics.
This PR creates a new `useErrorPageAnalytics` hook for pushing 404-related data to Segment. It is a near-copy of the [useErrorPageAnalytics hook in React Components](https://github.com/hashicorp/react-components/blob/main/packages/error-view/use-error-page-analytics.ts). The key difference is that we're adding the following …
> Create `useErrorPageAnalytics` hook

- .changeset/eighty-starfishes-occur.md
- packages/cli/generators/website/templates/pages/404.js
🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1202865459293217/f)
---
It was recently discovered that, across our various web properties, we make the following call:
`window.analytics.track(window.location.href, { ... } )`
The first parameter of the `track` method is used downstream in our various data warehouses to create a new table. Since we're using `window.location.href`, we're creating a table for _every_ URL that 404s. This is not ideal for analytics.
This PR leverages the new `useErrorPageAnalytics` hook (see [this PR](https://github.com/hashicorp/web-platform-packages/pull/86)) for pushing 404-related data to Segment. This PR replaces the `window.analytics.track` call on the 404 page with said hook.
> Use `useErrorPageAnalytics` hook on 404 page

- .changeset/wicked-readers-talk.md
- packages/analytics/add-cloud-link-handler/index.ts
Adds optional callback to `addCloudLinkHandler` to support analytics track calls for outbound links.
Example usage:
```ts
addCloudLinkHandler((destinationUrl) => {
window.analytics.track('Outbound link', {
destination_url: destinationUrl,
})
})
```
> feat(addCloudLinkHandler): adds optional callback to handler

- .changeset/nine-buckets-act.md
- packages/analytics/get-product-intent-from-url/index.test.js
- packages/analytics/get-product-intent-from-url/index.ts
🎟️ [Asana Task](https://app.asana.com/0/1202578820078349/1203095277649754/f)
---
Adds support for HCP returned as product intent.
If a product is in the URL, still return the product else if hcp is in the url return hcp.
```
https://developer.hashicorp.com => null
https://developer.hashicorp.com/hcp => hcp
https://developer.hashicorp.com/hcp/docs/terraform => terraform
```
> feat(getProductIntentFromURL): handle HCP in URLs

- jest.config.js
- package-lock.json
- package.json
- packages/analytics/__tests__/analytics-js-helpers.test.ts
- packages/analytics/get-product-intent-from-url/index.test.js
- packages/markdown-utils/markdown-to-html/index.test.ts
- packages/nextjs-plugin/src/get-hashicorp-packages.test.ts
- packages/remark-plugins/plugins/anchor-links/index.test.js
- packages/remark-plugins/plugins/paragraph-custom-alerts/index.test.js
- packages/remark-plugins/plugins/typography/index.test.js
- packages/util/geo/__tests__/index.test.ts
---
Support an in-between state where _some_ packages use ESM, while some do not. Splits our test run into two separate commands, `test:cjs` and `test:esm`. I also went ahead and updated jest to v29, and swapped from `ts-jest` to `swc` for speed.
> feat: update jest, support mixed esm and non-esm packages

- packages/content-conformance/src/rules/__tests__/ensure-valid-nav-data.test.ts
- packages/content-conformance/src/rules/ensure-valid-nav-data.js
- packages/content-conformance/src/test/utils.ts
---
- Ports our [existing nav-data validations](https://github.com/hashicorp/react-components/blob/main/packages/docs-sidenav/utils/validate-route-structure/index.ts) into a conformance rule.
- Adds a utility to test rules in isolation, called `testRule()`.
---
- https://app.asana.com/0/0/1203414786494809
> feat(content-conformance): add ensure-valid-nav-data rule

- .changeset/wicked-dolphins-beg.md
- packages/content-conformance/src/configs/base-docs.js
- packages/content-conformance/src/rules/__tests__/ensure-valid-link-format.test.ts
- packages/content-conformance/src/rules/ensure-valid-link-format.js
- packages/content-conformance/src/test/utils.ts
---
Ports over logic from the tutorials link format check to a conformance rule. The rule supports a configuration option called `isTutorials`, which we will set when configuring the rule to run in the tutorials repo.
Note: This rule is only concerned with the validity of the link structure, not necessarily that the links point to a valid location. We will rely on future rules / checks to ensure links are not broken.
---
- https://app.asana.com/0/0/1203757634522303
> feat(content-conformance): add ensure-valid-link-format rule

- .changeset/beige-mails-ring.md
- packages/analytics/add-anonymous-id-handler/index.ts
- packages/analytics/add-global-link-handler/index.ts
- packages/analytics/index.tsx
🎟️ [Asana Task](https://app.asana.com/0/1203227460033456/1203227460033463/f)
---
This PR introduces `addGlobalLinkHandler` to replace `addCloudLinkHandler` functionality and adds the passing of Segment Anonymous ID within the search params.
- Navigate to https://hashicorp-www-next-33szo9g6y-hashicorp.vercel.app/products/vault?utm_source=example
- Click Sign up for HCP Vault button in hero
- You should be taken to https://cloud.hashicorp.com/products/vault and ajs_aid, product_intent, and utm_source should be passed along as search params within the URL.
A bit harder to test is that those search params should persist in the URL across domains.
> feat(analytics): `addGlobalLinkHandler`

- .github/workflows/canary-release.yml
---
`changesets` will automatically deepen a shallow clone so that it can correctly generate changelogs and such. However, that functionality is fairly brittle, and will frequently cause infinite loops when attempting to deepen the checkout. Instead of that, this PR updates our checkout action to do a full clone (since that information is needed anyway), which prevents `changesets` from trying to do it itself (and failing).
> fix: use full clone for canary release

- .github/workflows/canary-release.yml
- .github/workflows/release.yml
Consolidating secret naming to align with `react-components`
> rename `PUBLISH_GITHUB_TOKEN` to `CHANGESETS_PAT`

- .changeset/rich-parents-rescue.md
- packages/analytics/use-page-view-analytics/index.tsx
- update fathom script domain
- version package
---
Fathom has had upstream issues with their custom domain provider failing to renew SSL certificates, and have advised us that we should switch to their default CDN URL `cdn.usefathom.com/script.js`
This PR replaces our custom `tarantula.hashicorp.com` url with Fathom's default
> Replace Fathom custom domain with default URL

- .github/workflows/canary-release.yml
- .github/workflows/release.yml
---
Commit is the result of: 'tsccr-helper -pin-all-workflows .'
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
Note, this unsolicited PR is a courtesy and has not been tested before submission.  The PR should be evaluated and merged by its responsible team.
> Bump all GitHub Actions and pin using TSCCR; avoid deprecated Node 12

- .changeset/serious-pants-lie.md
- packages/content-conformance/README.md
- packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/docs/partials/some-partial.mdx
- packages/content-conformance/src/__tests__/config.test.ts
- packages/content-conformance/src/__tests__/content-file.test.ts
- packages/content-conformance/src/__tests__/engine.test.ts
- packages/content-conformance/src/config.ts
- packages/content-conformance/src/content-file.ts
- packages/content-conformance/src/engine.ts
---
Updating content conformance config value `partialsDirectory` to `partialsDirectories` and makes it an array. This allows us to check for multiple directories, specifically for terraform's content source repositories that use a `docs/` directory.
> fix: update config value to partialsDirectories

- .changeset/green-forks-compare.md
- packages/tools/src/index.ts
---
This PR disables logging .env file loading when using `hc-tools`, which breaks scripts that expect the output to be JSON parseable.
> fix: disable env file logging

- .changeset/shy-roses-wait.md
- packages/cli/config/.eslintrc.js
This PR extends the jsx-a11y/alt-text rule to also look for Next.js Images.
> Extend jsx-a11y to also look for Next.js Images

- .changeset/slimy-moose-rest.md
- package-lock.json
- packages/remark-plugins/plugins/anchor-links/index.js
---
This PR adds a missing `.js` extension to an import statement that was missing it. `remark-plugins` is an es module, so all imports from the filesystem need to have the extension.
> fix: add missing js extension

- .github/workflows/canary-release.yml
- .github/workflows/release.yml
🎟️ Asana Task - None, fix for reported Github Action failures (e.g. [#1](https://github.com/hashicorp/web-platform-packages/actions/runs/9846586302/job/27186006321))
---
This PR replaces the CHANGESETS_PAT token with the always available GITHUB_TOKEN and sets it's permissions so that it can create PRs.
None, because we have no local tests for this workflow. 😢
> Replace CHANGESETS_PAT with github and give perms

- .github/workflows/canary-release.yml
- .github/workflows/release.yml
🎟️ Asana Task - None, fix for not enough permissions in previous fix. #269 
---
[We actually have what I believe are enough permissions on the default GHA token.](https://github.com/hashicorp/web-platform-packages/settings/actions#:~:text=Workflow%20permissions) And [setting specific permissions actually limits any non specified permissions:](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
> If you specify the access for any of these scopes, all of those that are not specified are set to none.
I also double checked the action that needs this permission [changesets/action README](https://github.com/changesets/action) and it looks like it should work with the default token.
Soooo try 2.
None, because we have no local tests for this …
> Give write permission to the GHA token

- .changeset/plenty-fans-suffer.md
- package-lock.json
- packages/nextjs-plugin/src/plugins/with-inline-svg-loader.ts
🎟️ [Asana Task](https://app.asana.com/0/1206815131022336/1203910559645521/f)
---
There is a problem on safari dev portal where a svg that is used as a background image is blurry. To fix this, I used the svg inline instead of as a background image. That worked in most places but on the hcp page, the svg was getting cut off. This was because the title svg being used was different from other products. This svg had a clip-path and the other product svgs do not. Since the new blurry svg and the title svg have a clip-path, there became a problem. Our svgo settings currently minify the ids on svgs to reduce size. However, if you have two svgs in the same spot, this can become a problem. The algorithm svgo uses is very simple and assigns the ids as a, b, c, ... Because of this, both svgs had a …
> fix: turn off cleanupIds for svgo loader
