.changeset/selfish-forks-clap.md, package-lock.json, packages/markdown-utils/package.json
---
This bumps the `@hashicorp/remark-plugins` dependency version in `@hashicorp/platform-markdown-utils`
=> chore: bump `remark-plugins`

.changeset/config.json
=> fix: update changesets repo config

.github/workflows/canary-release.yml
---
This copies https://github.com/hashicorp/react-components/blob/main/.github/workflows/canary-release.yml
=> chore: `Canary Release`

.changeset/hot-rabbits-yell.md, package-lock.json, package.json, packages/tools/README.md, packages/tools/package.json, packages/tools/scripts/add-deploy-preview-script/index.ts, packages/tools/scripts/add-deploy-preview-script/script.template.txt, packages/tools/src/index.ts, packages/tools/src/util.ts, packages/tools/tsconfig.json, readme.md
---
Introduces a new package, `@hashicorp/platform-tools`, which exposes an executable call `hc-tools`. This utility can execute packaged scripts found in the package, under `packages/tools/scripts`, or arbitrary TS scripts in the current working directory.
We often write one-off TS scripts and utilities in our repositories, which then require us to add `ts-node` and configuration to get them running. We also sometimes have a need to execute common scripts across all of our repositories. This package aims to solve for those two use cases.
Packaged script:
```
$ npx hc-tools add-deploy-preview-script waypoint
```
Writes a deploy script utility to `scripts/website-build.sh` for product repo deploy previews.
Arbitrary script:
```
$ npx hc-tools …
```
=> feat: Adds new platform-tools package

.changeset/twenty-phones-talk.md, package-lock.json, packages/configs/README.md, packages/configs/package.json, packages/configs/prettier.config.js, packages/configs/tsconfig/next.json
🎟️ [Asana Task](https://app.asana.com/0/0/1202025665826438/f)
---
Adds a new `@hashicorp/platform-configs` package to share basic config files that don't have any dependencies.
=> Add @hashicorp/platform-configs package

.changeset/bright-students-raise.md, package-lock.json, packages/tools/package.json, packages/tools/src/__tests__/__fixtures__/tsconfig-paths-env/scripts/my-script-custom-paths.ts, packages/tools/src/__tests__/__fixtures__/tsconfig-paths-env/tsconfig.paths.json, packages/tools/src/__tests__/index.test.ts, packages/tools/src/index.ts
---
Add a new `--project` option, which mirrors the behavior of `ts-node`'s same-named option. Passes `--skipProject` by default to ensure stable execution.
=> feat(tools): adds --project option, --skipProject by default

.github/workflows/release.yml
---
Use the service account PAT for the release workflow so that it can successfully open PRs
=> chore(release): use service account token

packages/analytics/README.md
---
Fixes analytics package README formatting that mades its way in.
=> fix: anayltics README formatting

.changeset/few-ducks-think.md, package-lock.json, packages/packer-plugins/package.json, packages/packer-plugins/src/fetch-plugin-docs.ts, packages/packer-plugins/src/parse-docs-zip.ts, packages/packer-plugins/src/parse-source-zip.ts
Use `@vercel/fetch` when fetching packer plugin content so we can get retries out of the box, which should reduce flaky build failures.
=> feat(packer-plugins): fetch retries on content fetch

.changeset/dull-steaks-learn.md, packages/edge-utils/lib/set-geo-cookie.ts
---
Fix type error resulting from using an older version of next.
=> fix(edge-utils): fix type error with old next types

.changeset/nine-swans-clap.md, package-lock.json, packages/postcss-config/package.json
---
Upgrades `postcss-preset-env` to get rid of the warning when used in a Next v12 project.
=> chore(deps): Upgrade postcss-preset-env

.changeset/four-clocks-move.md, packages/analytics/utm-params-capture/index.ts
🎟️ [Asana Task](https://app.asana.com/0/0/1202440941795901/1202695733775731/f)
---
Updating the list of UTM params we capture.
=> chore: update utm allow list

packages/analytics/package.json, packages/cli/package.json, packages/cms/package.json, packages/code-highlighting/package.json, packages/configs/package.json, packages/docs-mdx/package.json, packages/edge-utils/package.json, packages/markdown-utils/package.json, packages/nextjs-plugin/package.json, packages/packer-plugins/package.json, packages/postcss-config/package.json, packages/product-meta/package.json, packages/remark-plugins/package.json, packages/runtime-error-monitoring/package.json, packages/types/package.json, packages/util/package.json
---
Adds repository info to each package. This should allow dependabot, for example, to automatically find our generated changelogs.
Script for posterity:
<details>
<summary> Script </summary>
```ts
import fs from 'fs'
import path from 'path'
async function main() {
const packages = (
await fs.promises.readdir(path.join(process.cwd(), 'packages'), {
withFileTypes: true,
})
).filter((ent) => ent.isDirectory())
for (const pkg of packages) {
const packageJsonPath = path.join(
process.cwd(),
'packages',
pkg.name,
'package.json'
)
const packageJson = JSON.parse(
await fs.promises.readFile(packageJsonPath, { encoding: 'utf-8' })
)
if (!packageJson.repository) {
packageJson.repository = {
type: 'git',
url: 'https://github.com/hashicorp/web-platform-packages.git',
directory: …
```
=> chore: add repository info to each package

.changeset/slow-tables-roll.md, packages/analytics/README.md, packages/analytics/add-cloud-link-handler/index.ts, packages/analytics/index.tsx
Adds a new util to attach utm and product params to cloud URLs when present.
=> feat: `addCloudLinkHandler()`

.changeset/four-squids-rhyme.md, package-lock.json, packages/datocms-plugin-table/src/index.tsx
---
Add changeset for dato cms table plugin
=> Publish Dato Table Plugin

.changeset/three-poets-raise.md, package-lock.json, packages/docs-mdx/package.json
---
This PR bumps react components used in the `platform-docs-mdx` component to their latest respective versions.
Related https://github.com/hashicorp/react-components/pull/695
=> chore(deps): bump code-block and tabs

.changeset/fluffy-dogs-beam.md, packages/analytics/add-cloud-link-handler/index.ts
Adjust product intent search param from 'product' to 'product_intent'
=> chore(addCloudLinkHandler): change product intent key

.changeset/eight-jars-fetch.md, package-lock.json, packages/datocms-plugin-table/package.json, packages/datocms-plugin-table/src/components/TableEditor/index.tsx, packages/datocms-plugin-table/src/components/TableEditor/styles.module.css, packages/datocms-plugin-table/src/entrypoints/Modal/index.tsx, packages/datocms-plugin-table/src/index.tsx
Make some updates to the Dato Table Plugin:
- Change the display name from "Complex" to "Advanced"
- Fix the homepage link
- Change the color of the collapsible icon
- Add action buttons at the top in addition to bottom since editing in full screen is recommended and tables can get quite long so that option might get missed.
**Before**
**After**
=> chore: dato table plugin minor updates

.changeset/fair-masks-allow.md, packages/analytics/add-cloud-link-handler/index.ts
---
Includes pathName in url generation.
=> fix: include pathname in addCloudLinkHandler generation

.changeset/lucky-icons-judge.md, packages/tools/src/__tests__/__fixtures__/tsconfig-paths-env/scripts/my-script.ts, packages/tools/src/__tests__/index.test.ts, packages/tools/src/index.ts
---
Pass any provided CLI args to the invoked script.
=> feat(tools): pass CLI args to the called script

.changeset/famous-stingrays-itch.md, packages/analytics/add-cloud-link-handler/index.ts
---
Add checks for `target="_blank"` and `meta+clicks` on links and open in new window.
Fixes issue in https://github.com/hashicorp/dev-portal/pull/1137
=> fix(addCloudLinkHandler): add check for external link functionality

.changeset/serious-pants-draw.md, package-lock.json, packages/analytics/README.md, packages/analytics/__tests__/analytics-js-helpers.test.ts, packages/analytics/analytics-event-logger/index.ts, packages/analytics/analytics-js-helpers.ts, packages/analytics/index.tsx, packages/analytics/package.json
---
Porting a few analytics utilities from https://github.com/hashicorp/dev-portal/blob/main/src/lib/analytics.ts
[Formatted README](https://github.com/hashicorp/web-platform-packages/blob/brk.feat/analytics-helpers/packages/analytics/README.md#trackeventname-string-properties-recordsting-unknown)
=> feat: adds some analytics utilities

.changeset/many-carrots-cover.md, packages/analytics/analytics-js-helpers.ts
=> fix: typeof undefined as a string

.changeset/giant-oranges-impress.md, jest.config.js, package-lock.json, package.json, packages/configs/README.md, packages/configs/jest/__mocks__/graphql-fragment-mock.js, packages/configs/jest/config.js, packages/configs/package.json
---
Adds a shared jest config for use across our apps and repositories. This should minimize duplicate configuration and make it easier to keep our testing environments consistent. Dog-fooding the configuration by using it in this repository.
---
- https://app.asana.com/0/0/1201024261811843
=> feat(configs): add shared jest config

.changeset/many-rockets-listen.md, package-lock.json, packages/content-conformance/package.json, packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/data/nav-data.json, packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/data/nav-data.yaml, packages/content-conformance/src/__tests__/data-file.test.ts, packages/content-conformance/src/__tests__/engine.test.ts, packages/content-conformance/src/data-file.ts, packages/content-conformance/src/engine.ts
🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1203332374839498/f)
---
Implement the `DataFile` class. Supports `.json` and `.yaml` files. The resulting object is immutable and accessible via `.content()` for use in rules.
=> feat(content-conformance): implement DataFile

package-lock.json, packages/content-conformance/README.md, packages/content-conformance/package.json, packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/content/has-frontmatter.mdx, packages/content-conformance/src/__tests__/config.test.ts, packages/content-conformance/src/__tests__/content-file.test.ts, packages/content-conformance/src/__tests__/engine.test.ts, packages/content-conformance/src/__tests__/runner.test.ts, packages/content-conformance/src/content-file.ts
🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1203332374839502/f)
---
This updates `ContentFile` to parse frontmatter from files
=> feat(content-file): parses frontmatter

packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/content-conformance-severity.config.js, packages/content-conformance/src/__tests__/engine.test.ts, packages/content-conformance/src/__tests__/rules.test.ts, packages/content-conformance/src/__tests__/runner.test.ts, packages/content-conformance/src/config.ts, packages/content-conformance/src/content-file.ts, packages/content-conformance/src/engine.ts, packages/content-conformance/src/rules.ts, packages/content-conformance/src/runner.ts, packages/content-conformance/src/types.ts
---
Respect the rule level defined in config when calling `context.report()`. This ensures we can properly discern between warnings and errors, and handle the result accordingly.
---
- https://app.asana.com/0/0/1203332374839504
=> feat: respect rule levels defined in config

packages/content-conformance/README.md, packages/content-conformance/src/__tests__/config.test.ts, packages/content-conformance/src/__tests__/content-file.test.ts, packages/content-conformance/src/config.ts, packages/content-conformance/src/content-file.ts, packages/content-conformance/src/engine.ts
---
Detect if a file is a partial when initializing `ContentFile` and sets `isPartial` appropriately.
=> feat(content-conformance): detect partials

packages/content-conformance/README.md, packages/content-conformance/src/__tests__/__fixtures__/basic-with-content-files/content-conformance-preset.config.js, packages/content-conformance/src/__tests__/__fixtures__/invalid-config/content-conformance-invalid-preset.config.js, packages/content-conformance/src/__tests__/config.test.ts, packages/content-conformance/src/config.ts, packages/content-conformance/src/configs/base-docs.js, packages/content-conformance/src/configs/base-mdx.js, packages/content-conformance/src/runner.ts, packages/content-conformance/src/utils.ts
---
Support configuration presets, both via extension in a local config file using the `preset` property, or by passing it in via the runner's options.
---
- https://app.asana.com/0/0/1203332374839506
=> feat(content-conformance): support config extension

package-lock.json, packages/content-conformance/README.md, packages/content-conformance/package.json, packages/content-conformance/src/__tests__/runner.test.ts, packages/content-conformance/src/runner.ts
---
Support multiple different reporter types. Currently `json` and `text` are implemented, but we will be able to add additional reporter types going forward.
---
- https://app.asana.com/0/0/1203332374839512
=> feat(content-conformance): add support for multiple reporters

.changeset/weak-points-warn.md, packages/content-conformance/src/configs/base-docs.js, packages/content-conformance/src/runner.ts
---
Adds `dataFileGlobPattern` to the `base-docs` preset. Also fixes a minor bug with the runner status implementation.
=> feat(content-conformance): add dataFileGlobPattern, fix runner status

package-lock.json, package.json, packages/content-conformance/package.json, packages/content-conformance/src/__tests__/engine.test.ts, packages/content-conformance/src/rules/__tests__/ensure-valid-nav-paths.test.ts, packages/content-conformance/src/rules/ensure-valid-nav-paths.js, packages/content-conformance/src/test/utils.ts
This adds a `ensure-valid-nav-paths` data-file **rule** to ensure `...-nav-data.json` files' individual nodes have corresponding content-files
---
=> [content-conformance] `ensure-valid-nav-paths`

.changeset/young-clocks-train.md, packages/content-conformance/src/configs/base-docs.js
=> [content-conformance] update `base-mdx` - add `ensure-valid-nav-paths`

.changeset/gold-boats-speak.md, package-lock.json, packages/content-conformance/package.json, packages/content-conformance/src/__tests__/runner.test.ts, packages/content-conformance/src/reporters/markdown-reporter.ts, packages/content-conformance/src/runner.ts
---
Add a reporter to output formatted markdown intended to be posted as a GitHub PR comment.
---
- https://app.asana.com/0/0/1203331966445549
=> feat(content-conformance): add GH comment reporter

packages/content-conformance/src/__tests__/cli.test.ts
🎟️ [Asana Task](https://app.asana.com/0/1203331966445516/1203407660528094)
---
Found an issue with path to content in tests, and added the getFixturePath util function to test file.
=> getFixturePath util & fix content paths in tests

.changeset/eighty-keys-sort.md, package-lock.json, packages/content-conformance/README.md, packages/content-conformance/package.json, packages/content-conformance/src/configs/base-docs.js, packages/content-conformance/src/rules/__tests__/no-link-in-heading.test.ts, packages/content-conformance/src/rules/no-link-in-heading.js, packages/content-conformance/src/test/utils.ts
---
Add a rule to ensure we do not add links to heading elements. This can mess with our anchor link generation, and coupled with that the anchor links can introduce accessibility challenges.
---
- https://app.asana.com/0/0/1203555682638509
=> feat(content-conformance): add no-link-in-heading rule

.changeset/lovely-bikes-sparkle.md, package-lock.json, packages/nextjs-plugin/src/__fixtures__/monorepo/apps/site/package.json, packages/nextjs-plugin/src/__fixtures__/package-json/package.json, packages/nextjs-plugin/src/get-hashicorp-packages.test.ts, packages/nextjs-plugin/src/get-hashicorp-packages.ts
---
Help better support running in a monorepo by checking for dependencies in `package.json`, in addition to traversing `node_modules`. This can help when dependencies might be hoisted to the workspace root.
=> feat(nextjs-plugin): make HC package detection work in a monorepo

.changeset/real-cougars-brush.md, packages/content-conformance/src/__tests__/config.test.ts, packages/content-conformance/src/configs/base-docs.js
---
Support the directory pattern that Terraform's docs repositories are using: `docs/**/*.mdx`
---
- https://app.asana.com/0/0/1203642186481288
=> handle docs/**/*.mdx for terraform repos

.changeset/new-elephants-punch.md, packages/content-conformance/src/configs/base-docs.js, packages/content-conformance/src/rules/__tests__/no-unlinked-pages.test.ts, packages/content-conformance/src/rules/no-unlinked-pages.js, packages/content-conformance/src/test/utils.ts
---
Adds a rule to validate that no unlinked pages exist in the content directory. The approach was to create a content file rule and check that its path has a matching path in the nav data, so the violations are associated with the content file. Nav data paths are pre-computed for easy checking across many content files.
---
- https://app.asana.com/0/0/1203555682638497
=> feat(content-conformance): no-unlinked-pages rule

.changeset/stupid-falcons-flow.md, packages/content-conformance/src/__tests__/cli.test.ts, packages/content-conformance/src/cli.ts, packages/content-conformance/src/rules/ensure-valid-frontmatter.js, packages/content-conformance/src/runner.ts
---
Tweaking the CLI output a little bit based on ✨ vibes ✨ .
Basic:
Success:
Passing files explicitly:
Errors and warnings:
I also updated the frontmatter rule to have a more helpful message.
=> feat(content-conformance): tweak CLI output

.changeset/curly-scissors-rhyme.md, packages/integrations-hcl/README.md, packages/integrations-hcl/__tests__/load-filesystem-integration.test.ts, packages/integrations-hcl/index.ts, packages/integrations-hcl/lib/generated/IntegrationsAPI.ts, packages/integrations-hcl/lib/generated/core/OpenAPI.ts, packages/integrations-hcl/lib/generated/core/request.ts, packages/integrations-hcl/lib/generated/request.ts.template, packages/integrations-hcl/lib/generated/services/IntegrationFlagsService.ts, packages/integrations-hcl/lib/generated/services/IntegrationReleaseComponentsService.ts, packages/integrations-hcl/lib/generated/services/IntegrationReleasesService.ts, packages/integrations-hcl/lib/generated/services/IntegrationsService.ts, packages/integrations-hcl/lib/generated/services/NotifyReleaseService.ts, packages/integrations-hcl/lib/generated/services/VariableGroupConfigsService.ts, packages/integrations-hcl/lib/generated/services/VariableGroupsService.ts, packages/integrations-hcl/lib/generated/services/VariablesService.ts
This is follow up work to breaking API changes introduced in:
- https://github.com/hashicorp/integrations-api/pull/79
---
=> (integrations-hcl) Handle Breaking API changes

.changeset/lazy-owls-wonder.md, packages/cli/markdown-blocks/editing-markdown.md
---
Adds a note on running content checks locally to the `editing-markdown` docs block.
=> feat(cli): Add docs on content checks to the editing-markdown block

.changeset/smart-carrots-leave.md, packages/content-conformance/src/__tests__/runner.test.ts, packages/content-conformance/src/reporters/markdown-reporter.ts, packages/content-conformance/src/rules/ensure-valid-link-format.js
---
Fix formatting of the markdown reporter. Shifts parse errors to render above the table as they have the tendency to be multiple lines.
Example output: https://github.com/hashicorp/mktg-content-workflows/actions/runs/4118101205#summary-11178176279
=> fix(content-conformance): adjust markdown reporter

.copywrite.hcl
---
Adds a copywrite config to exclude our forked copy of `next-optimized-images`
=> chore: add copywrite config to exclude next-optimized-images

packages/analytics/__tests__/analytics-js-helpers.test.ts, packages/analytics/get-product-intent-from-url/index.test.js, packages/util/geo/__tests__/index.test.ts
---
Moves `jest-environment` directives to single-line comments to fix a conflict with copyright header generation.
x-ref slack thread: https://hashicorp.slack.com/archives/C03CR2GBBB2/p1677519065115729
=> chore: move jest-environment declarations to single line comments

packages/content-conformance/README.md, packages/content-conformance/src/index.ts, packages/content-conformance/src/types.ts, readme.md
---
Expands documentation on writing rule executors now that things are a little more stable.
=> docs(content-conformance): add section on writing rules

.changeset/lovely-kids-press.md, packages/content-conformance/src/rules/__tests__/ensure-valid-link-format.test.ts, packages/content-conformance/src/rules/ensure-valid-link-format.js
🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1204109450984820/f)
---
Remove the check for fully-qualified developer links in `ensure-valid-link-format`. There are legitimate use cases for fully-qualified links and so we do not want to disallow them.
=> chore: remove check for full developer links from ensure-valid-link-format

.changeset/blue-melons-cry.md, packages/integrations-hcl/CHANGELOG.md, packages/integrations-hcl/__tests__/__fixtures__/builtin/docker/metadata.hcl, packages/integrations-hcl/__tests__/load-filesystem-integration.test.ts, packages/integrations-hcl/index.ts, packages/integrations-hcl/schemas/integration.ts, packages/integrations-hcl/schemas/metadata.hcl.ts
=> Update schema for components from flat array to obj

.changeset/curvy-terms-rescue.md, package-lock.json, packages/code-highlighting/highlight-data/index.ts, packages/code-highlighting/highlight-data/traverse.ts
---
This PR updates the TS types for `highlightData` to retain the original passed TS type.
=> feat: retain original input type

.changeset/polite-ghosts-call.md, jest.config.js, package-lock.json, packages/markdown-utils/index.test.js, packages/markdown-utils/index.ts, packages/markdown-utils/markdown-to-html/index.ts, packages/markdown-utils/markdown-to-inline-html/index.js, packages/markdown-utils/markdown-to-inline-html/index.test.js, packages/markdown-utils/package.json, packages/remark-plugins/plugins/paragraph-custom-alerts/index.js, packages/remark-plugins/plugins/paragraph-custom-alerts/index.test.js
=> fix: emit HTML instead of MDX

.changeset/large-months-mix.md, package-lock.json, packages/tools/package.json, packages/tools/scripts/next-build-webpack-only/index.ts
=> feat: find the next executable in monorepos

.changeset/silly-lions-lay.md, package-lock.json, packages/cli/package.json
---
---
- https://app.asana.com/0/0/1204326750912339
=> chore(cli): bump `prettier`

.changeset/cyan-dryers-happen.md, packages/tools/scripts/next-touched-pages/index.ts
---
This PR adds monorepo support to `next-touched-pages`.
=> feat: add support for being run in a subdirectory

.changeset/proud-windows-glow.md, package-lock.json, packages/analytics/analytics-event-logger/index.ts, packages/types/index.d.ts, packages/types/package.json
---
Updates types for `window.analytics` by removing an old `@types/` library and adopting times from the current `@segment/analytics-next` package.
=> chore: update window.analytics types

.changeset/loud-moles-do.md, packages/cli/markdown-blocks/deployment.md, packages/cli/markdown-blocks/editing-markdown.md, packages/cli/markdown-blocks/local-development.md
---
Update casing for some words in our markdown blocks.
=> chore: update casing for some words

.changeset/rich-seahorses-draw.md, packages/analytics/add-global-link-handler/index.ts, packages/analytics/analytics-js-helpers.ts
---
Fixes the return type of `getSegmentAnonymousId()` to align with the underlying segment types.
=> chore(analytics): fix `getSegmentAnonymousId()` return type

.changeset/wise-days-suffer.md, package-lock.json, packages/markdown-utils/package.json
---
This PR removes `@mdx-js/react` from `@hashicorp/platform-markdown-utils`, which wasn't being used (and causes peerDeps issues in projects with React v18).
=> chore(deps): remove unused @mdx-js/react dependency

.changeset/smart-queens-rush.md, packages/integrations-hcl/strategies/nomad-pack/load_pack_directory.ts, packages/integrations-hcl/strategies/nomad-pack/metadata.hcl.ts
- Allows for `pack.name` to be overridden via `integration.name`
- Removes the first line if it's an H1 in the README
=> A few small Nomad Pack consumption adjustments

.github/workflows/canary-release.yml, .github/workflows/release.yml
---
---
- https://app.asana.com/0/0/1204652324894701
=> chore: use latest changesets/action

.changeset/calm-seals-type.md, packages/cli/markdown-blocks/editing-markdown.md
🎟️ [Asana Task](https://app.asana.com/0/1204334492689024/1204921235104818/f)
---
Updates docs template to share the themed image syntax. Related to https://github.com/hashicorp/dev-portal/pull/2030 & https://github.com/hashicorp/mktg-content-workflows/pull/405
=> chore: Adds themed image docs

.changeset/silver-hats-sniff.md, packages/cli/markdown-blocks/editing-markdown.md
---
This PR updates the GitHub team name from `digital-marketing` to `web-presence` inside the template Markdown files that are used to generate the `website/README.md` file within our products' `website` folder.
=> fix: update web presence github team name

.github/workflows/canary-release.yml, .github/workflows/release.yml, .github/workflows/test.yml
---
This PR bumps all GitHub Actions workflows to the latest versions trusted by TSCCR.
---
- https://app.asana.com/0/0/1207233798525123
=> chore(deps): bump all workflows to latest trusted versions

packages/analytics/add-global-link-handler/index.ts
🎟️ [Asana Task](https://app.asana.com/0/1206176289707208/1207760701177754/f)
This PR fixes an error caused by the not null assertion (https://github.com/hashicorp/web/pull/1314#issuecomment-2218296284) 
This error is being logged on the client in production so it's worth the refactor
=> fix(analytics/add-global-handler): check if value exists🔍

.changeset/metal-cars-peel.md
=> chore: add changeset add-global-analytics patch
